#!/bin/bash

# ==============================================================================
# Headless Dashboard - Setup Script
# ==============================================================================
# Creates .env file with secure random secrets
# Run: chmod +x setup.sh && ./setup.sh

set -e

ENV_FILE=".env"
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Headless Dashboard - Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠ .env file already exists.${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Generate secure secrets
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)
DB_PASSWORD=$(openssl rand -base64 24 2>/dev/null || head -c 24 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)

echo "Generating secure secrets..."

# Create .env file
cat > "$ENV_FILE" << EOF
# ==============================================================================
# HEADLESS DASHBOARD - Environment Configuration
# ==============================================================================
# Generated by setup.sh on $(date)

# ------------------------------------------------------------------------------
# Database Configuration
# ------------------------------------------------------------------------------
DB_USER=dashboard
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=dashboard

# ------------------------------------------------------------------------------
# Security
# ------------------------------------------------------------------------------
# JWT Secret - Auto-generated secure random string
JWT_SECRET=${JWT_SECRET}

# ------------------------------------------------------------------------------
# URLs & Ports
# ------------------------------------------------------------------------------
# Port mappings
API_PORT=4000
UI_PORT=3000

# Frontend URL (used for SSO redirects)
FRONTEND_URL=http://localhost:3000

# API Base URL (used for SSO callback)
API_BASE_URL=http://localhost:4000

# CORS Origins (comma-separated list)
CORS_ORIGINS=http://localhost:3000

# ------------------------------------------------------------------------------
# Frontend Configuration
# ------------------------------------------------------------------------------
# API URL for frontend (must be accessible from browser)
# For production behind reverse proxy: https://your-domain.com/api
NEXT_PUBLIC_API_URL=http://localhost:4000/api

# Icon CDN source (Selfh.st icons)
NEXT_PUBLIC_ICON_SOURCE=https://cdn.jsdelivr.net/gh/selfhst/icons/png/

# ------------------------------------------------------------------------------
# Environment
# ------------------------------------------------------------------------------
NODE_ENV=production

# ==============================================================================
# PRODUCTION DEPLOYMENT - Update these for your domain:
# ==============================================================================
# FRONTEND_URL=https://dashboard.example.com
# API_BASE_URL=https://dashboard.example.com
# NEXT_PUBLIC_API_URL=https://dashboard.example.com/api
# CORS_ORIGINS=https://dashboard.example.com
EOF

echo ""
echo -e "${GREEN}✓ Created .env file with secure secrets${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo "  • Database user: dashboard"
echo "  • Database password: [auto-generated]"
echo "  • JWT secret: [auto-generated]"
echo "  • UI port: 3000"
echo "  • API port: 4000"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Start the dashboard:"
echo "     docker compose up -d"
echo ""
echo "  2. Open http://localhost:3000"
echo ""
echo "  3. Login with default credentials:"
echo "     Email: admin@localhost"
echo "     Password: admin"
echo ""
echo -e "${YELLOW}⚠ Change the default password after first login!${NC}"
echo ""
echo -e "${BLUE}For production deployment, edit .env and update:${NC}"
echo "  • FRONTEND_URL"
echo "  • API_BASE_URL"
echo "  • NEXT_PUBLIC_API_URL"
echo "  • CORS_ORIGINS"
echo ""
